# Generated by Django 5.2.3 on 2025-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolos_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AddField(
            model_name='bolo',
            name='categorias',
            field=models.ManyToManyField(related_name='bolos', to='bolos_pedidos.categoria'),
        ),
    ]
