# Generated by Django 5.2.3 on 2025-08-20 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolos_pedidos', '0002_categoria_bolo_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.CreateModel(
            name='Imagembolos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='bolos/galeria/')),
                ('bolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='bolos_pedidos.bolo')),
            ],
        ),
    ]
