# Generated by Django 5.2.3 on 2025-08-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolos_pedidos', '0003_alter_categoria_options_imagembolos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='nome',
        ),
    ]
