# Generated by Django 5.2.3 on 2025-08-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolos_pedidos', '0004_rename_nome_categoria_categoria_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagembolos',
            new_name='ImagemBolo',
        ),
        migrations.AlterField(
            model_name='bolo',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem principal do bolo', null=True, upload_to='bolos/'),
        ),
    ]
