# Generated by Django 5.2.3 on 2025-08-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolos_pedidos', '0005_rename_imagembolos_imagembolo_alter_bolo_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Um título para a imagem, ex: 'Bolo de Casamento Floral'", max_length=100)),
                ('imagem', models.ImageField(upload_to='portfolio/')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da imagem.', null=True)),
            ],
            options={
                'verbose_name': 'Imagem do Portfólio',
                'verbose_name_plural': 'Imagens do Portfólio',
                'ordering': ['-id'],
            },
        ),
    ]
